version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'car_service'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
        # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
        - my-db:/var/lib/mysql
        - ./init.sql:/data/application/init.sql
volumes:
   my-db: